// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class GoogleMapScreen : UIViewController
	{
		public GoogleMapScreen (IntPtr handle) : base (handle)
		{
		}
	}
}
