// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Foundation;

namespace FrameWorkApp
{
	public partial class TripSummaryScreen : UIViewController
	{
		TripHistoryReadWrite tripHistory = new TripHistoryReadWrite(false);

		public TripSummaryScreen (IntPtr handle) : base (handle)
		{
			//Add Recent trip to History
			Console.WriteLine ("Adding Most Recent Trip to History");
			tripHistory.addDataToTripHistoryFile (new Trip(DateTime.Now, StopScreenn.thisTripDataFile.readDataFromTripFile().Length));
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			//Updates tripSummaryEventLabel displaying events from this trip
			tripSummaryEventsLabel.Text = StopScreenn.thisTripDataFile.readDataFromTripFile ().Length.ToString();
			distanceLabel.Text = StopScreenn.distanceTraveledForCurrentTrip.ToString ();
		}

		partial void toHome (NSObject sender)
		{
			StopScreenn.coordList.Clear();
			DismissModalViewControllerAnimated(true);
			StopScreenn.thisTripDataFile = new TripCoordinateReadWrite (true);
		}

		public override void ViewDidUnload ()
		{
			StopScreenn.thisTripDataFile = new TripCoordinateReadWrite (true);
		}
	}
}
