// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Foundation;
using System.Collections.Generic;
using MonoTouch.CoreLocation;

namespace FrameWorkApp
{
	public partial class TripSummaryScreen : UIViewController
	{
		SDMFileManager fileManager = new SDMFileManager();
		RawGPS rawGPS = new RawGPS();
<<<<<<< HEAD
=======
		public static CLLocationCoordinate2D[] events;

>>>>>>> AddingSaveFeaturesToTripSummaryPage
		public TripSummaryScreen (IntPtr handle) : base (handle)
		{
			//Add Recent trip to History
			fileManager.addDataToTripLogFile(new Trip(DateTime.Now, StopScreenn.fileManager.readDataFromTripEventFile().Length));
<<<<<<< HEAD
=======
			events=fileManager.readDataFromTripEventFile ();
			fileManager.clearCurrentTripEventFile();
			fileManager.clearCurrentTripDistanceFile();
>>>>>>> AddingSaveFeaturesToTripSummaryPage
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			//Updates tripSummaryEventLabel displaying events from this trip
<<<<<<< HEAD
			tripSummaryEventsLabel.Text = StopScreenn.fileManager.readDataFromTripEventFile ().Length.ToString();
			distanceLabel.Text = rawGPS.convertMetersToKilometers(rawGPS.CalculateDistanceTraveled(new List<CLLocation>(fileManager.readDataFromTripDistanceFile()))).ToString();
			hardBrakesLabel.Text = StopScreenn.numberHardStops.ToString ();
			numHardStartLabel.Text = StopScreenn.numberHardStarts.ToString ();
			fastAccelsLabel.Text = StopScreenn.numberHardStarts.ToString ();
			double total = (StopScreenn.numberHardStops) + (StopScreenn.numberHardStarts);
			totalBreakAcessLabel.Text = total.ToString ();
=======
			//tripSummaryEventsLabel.Text = StopScreenn.fileManager.readDataFromTripEventFile ().Length.ToString();
			tripSummaryEventsLabel.Text = events.Length.ToString();
			distanceLabel.Text = rawGPS.convertMetersToKilometers(rawGPS.CalculateDistanceTraveled(new List<CLLocation>(fileManager.readDataFromTripDistanceFile()))).ToString();

>>>>>>> AddingSaveFeaturesToTripSummaryPage
		}

		partial void toHome (NSObject sender)
		{
			StopScreenn.coordList.Clear();
			DismissModalViewControllerAnimated(true);
<<<<<<< HEAD
			StopScreenn.fileManager.clearCurrentTripEventFile();
			StopScreenn.fileManager.clearCurrentTripDistanceFile();
=======
>>>>>>> AddingSaveFeaturesToTripSummaryPage

		}

	}
}
